# MediaWiki with MariaDB and fuseki
#
# Access via "http://localhost:8080"
version: '3'
services:
  database:
    build:
      context: ./enigma-db/
      dockerfile: Dockerfile
    restart: always
  mediawiki:
    build:
      context: ./enigma-wiki/
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - database
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - ${PORT}:80
    volumes:
      - ./images:/var/www/html/images
