# MediaWiki with MariaDB and fuseki
#
# Access via "http://localhost:8080"
version: '3'
services:
  database:
    build:
      context: ./enigma-db/
      dockerfile: Dockerfile
    restart: always
  mediawiki:
    build:
      context: ./enigma-wiki/
      dockerfile: Dockerfile
    extra_hosts:
+     - "host.docker.internal:host-gateway"
    restart: always
    ports:
      - 8083:80
    links:
      - database
      #- fuseki
    #volumes:
      #- /var/www/html/images
#  fuseki:
#    image: stain/jena-fuseki
#    restart: always
